title: suz.al
description: Styled with Royal Velvet


markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-reading-time

# Ensure ALL markdown files (including in subfolders like /zines/)
# get processed with the default layout unless they override it.
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
